'use strict';

module.exports = {
  INTEGER: 'INTEGER',
  BIGINT: 'BIGINT',
  DECIMAL: 'DECIMAL',
  REAL: 'REAL',
  DOUBLE: 'DOUBLE',
  BOOLEAN: 'BOOLEAN',
  CHAR: 'CHAR',
  VARCHAR: 'VARCHAR',
  DATE: 'DATE',
  TIMESTAMP: 'TIMESTAMP',
  TIMESTAMPZ: 'TIMESTAMPZ',
};
